project_name: nextword
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}"
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
